### ISSUE TITLE
How to use startRecord method?

### ISSUE THREAD

**Issue by unigeniee** [baka3k/IjkPlayerRecorder#1]
Dear author,
I'd like to ask how to use this startRecord for iOS?
Is it ready to use? If it works for now, I really appreciate it coz same method doesn't exist on the original git repo

`self.player.startRecord(withFileName: "xxx")`

What should I use with this parameter **withFileName** ?

**Comment by baka3k** [comment]
Hi,
It means your path folder you want to place on your device
Hope this helps

**Comment by unigeniee** [comment]
I tried to point out a folder in iOS to save it as the following. But after that, I dowloaded the data container of the application, nothing in it.
What should I do to the correct way?
`let documentDirURL = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: true)

        self.player.startRecord(withFileName: documentDirURL.absoluteString)

        Timer.scheduledTimer(withTimeInterval: 10, repeats: false) { timer in
            self.player.stopRecord()
            print("stopRecord", documentDirURL.absoluteString)
        }`

by the way, I'd like to ask again, is **startRecord** READY to use on iOS yet?

**Comment by baka3k** [comment]
Im not an IOS developer, but I believe we can use startRecord on IOS
because it's function of IJKPlayer, Recorder function written in C/C++ layer
It's not relate android framework or ios framework
on android, we must create JNI to work with IJKPlayer(Record, play..etc)
IOS will be simpler

Vào Th 4, 8 thg 4, 2020 vào lúc 08:50 unigeniee <notifications@github.com>
đã viết:
